# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_roast = QtWidgets.QLabel(Dialog)
        self.label_roast.setObjectName("label_roast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_roast)
        self.comboBox_roast = QtWidgets.QComboBox(Dialog)
        self.comboBox_roast.setObjectName("comboBox_roast")
        self.comboBox_roast.addItem("")
        self.comboBox_roast.addItem("")
        self.comboBox_roast.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_roast)
        self.label_ground = QtWidgets.QLabel(Dialog)
        self.label_ground.setObjectName("label_ground")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_ground)
        self.comboBox_type = QtWidgets.QComboBox(Dialog)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.label_taste = QtWidgets.QLabel(Dialog)
        self.label_taste.setObjectName("label_taste")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_taste)
        self.textEdit_taste = QtWidgets.QTextEdit(Dialog)
        self.textEdit_taste.setObjectName("textEdit_taste")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit_taste)
        self.label_price = QtWidgets.QLabel(Dialog)
        self.label_price.setObjectName("label_price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_price)
        self.lineEdit_price = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_price)
        self.label_volume = QtWidgets.QLabel(Dialog)
        self.label_volume.setObjectName("label_volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_volume)
        self.lineEdit_volume = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_volume)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_save = QtWidgets.QPushButton(Dialog)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление/Редактирование кофе"))
        self.label_name.setText(_translate("Dialog", "Название:"))
        self.label_roast.setText(_translate("Dialog", "Степень обжарки:"))
        self.comboBox_roast.setItemText(0, _translate("Dialog", "Светлая"))
        self.comboBox_roast.setItemText(1, _translate("Dialog", "Средняя"))
        self.comboBox_roast.setItemText(2, _translate("Dialog", "Темная"))
        self.label_ground.setText(_translate("Dialog", "Тип:"))
        self.comboBox_type.setItemText(0, _translate("Dialog", "Молотый"))
        self.comboBox_type.setItemText(1, _translate("Dialog", "В зернах"))
        self.label_taste.setText(_translate("Dialog", "Описание вкуса:"))
        self.label_price.setText(_translate("Dialog", "Цена:"))
        self.label_volume.setText(_translate("Dialog", "Объем упаковки:"))
        self.button_save.setText(_translate("Dialog", "Сохранить"))
        self.button_cancel.setText(_translate("Dialog", "Отмена"))
